accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

main/urls.py
from django.urls import path, reverse_lazy
from . import views




app_name='main'
urlpatterns = [
    path('profile/<int:user_id>/', views.ProfilePageView.as_view(), name='profile'),
    path('iwade_lesson/list', views.LessonListView.as_view(), name='lesson_list'),
    path('profile/picture/<int:user_id>/', views.profile_stream_file, name='profile_picture'),
    path('button/<int:pk>/', views.ButtonPageView.as_view(), name='button_page'),
    path('button/<int:pk>/delete/<int:lesson_pk>/', views.ButtonDeleteView.as_view(success_url=reverse_lazy('main:button_page')), name='button_delete'),
    path('lesson/create/', views.LessonCreateView.as_view(), name='lesson_create'),
    path('lesson/<int:pk>/update/', views.LessonUpdateView.as_view(), name='lesson_update'),
    path('lesson/picture/<int:pk>/', views.stream_file, name='lesson_picture'),
    path('lesson/<int:pk>/delete', views.LessonDeleteView.as_view(success_url=reverse_lazy('main:lesson_list')), name='lesson_delete'),
    path('participation_increase/<int:pk>/<int:click_id>/', views.ParticipationIncreaseView.as_view(), name='participation_increase'),
    path('delete/<int:pk>/', views.AccountDeleteView.as_view(), name='delete_account'),
    path('', views.BjjLessonListView.as_view(), name='bjj_lesson_list'),
    path('set-user-limit/', views.SetUserLimitView.as_view(), name='set_user_limit'),
    path('reset_monthly_counts/', views.ResetMonthlyCountsView.as_view(), name='reset_monthly_counts'),
    path('profile/<int:user_id>/participation_count/', views.ParticipationCountView.as_view(), name='participation_count'),
    path('add_users_to_lessons/', views.AddUsersToLessonsView.as_view(), name='add_users_to_lessons'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),# Keep
]


# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]


# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    # Jiu jitsu belt colors for each member.
    BELT_CHOICES = (
        ('White', 'White'),
        ('Blue', 'Blue'),
        ('Purple', 'Purple'),
        ('Brown', 'Brown'),
        ('Black', 'Black'),
    )

    # Member types for each member.
    MEMBER_TYPE_CHOICES = (
        ('Fivedays', 'Fivedays'),
        ('Eightdays', 'Eightdays'),
        ('Regular', 'Regular'),
    )

    # Number of stripes on the belt for each member.
    STRIPE_CHOICES = (
        (0, '0 stripes'),
        (1, '1 stripe'),
        (2, '2 stripes'),
        (3, '3 stripes'),
        (4, '4 stripes'),
    )

    # Which gym each member belongs too.
    GYM_CHOICES = (
        ('Kix', 'Kix'),
        ('Iwade', 'Iwade'),
        ('Both', 'Both'),
    )

    belt = models.CharField(max_length=20, choices=BELT_CHOICES, default='White')
    stripes = models.IntegerField(choices=STRIPE_CHOICES, default=0)
    member_type = models.CharField(max_length=20, choices=MEMBER_TYPE_CHOICES, default='Regular')
    gym_choice = models.CharField(max_length=20, choices=GYM_CHOICES, default='Kix')
    date_of_birth = models.DateField(blank=True, null=True)
    # date_of_birth is currently not being used, but might be used later upon request.
    profile_picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    # profile_picture and content_type are for upploading and streaming a picture for the user.
    # I got this from dj4e django tutorials assignments"
    user_limit = models.IntegerField(default=1000)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    # A signupform Using djangos built in UserCreationForm requiring username password and password confirmation.
    # Using widget to make the input form nice and uniform.

    username = forms.CharField(
        label="Username",
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2')

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib import messages


def signup(request):
    # Function for signing up using a custom form that uses djangos built in auth system.
    # It logs you in automatically upon success and redirects you to the Kix school schedule.
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main:profile', user_id=user.id)
    else:
        form = CustomUserCreationForm()
    if form.errors:
        messages.error(request, 'Username or Password are invalid. Please try again.')
    return render(request, 'accounts/signup.html', {'form': form})

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <!-- Add your CSS stylesheets or links here -->
    {% load static %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous" defer></script>

<link href="{% static 'accounts/log_sign.css' %}" rel="stylesheet">

</head>
<body>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<br>
<br>
<form method="post">
{% csrf_token %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card-group mb-0">
          <div class="card p-4">
            <div class="card-body">
              <h1>Login</h1>
              <p class="text-muted">Login and manage users</p>
              <div class="input-group mb-3">
                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                {{ form.username }}
              </div>
              <div class="input-group mb-4">
                <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                {{ form.password }}
              </div>
              <div class="row">
                <div class="col-6">
                  <button type="submit" class="btn btn-primary px-4">Login</button>
                </div>
                <div class="col-6 text-right">
                  <button type="button" class="btn btn-link px-0"></button>
                </div>
              </div>
            </div>
          </div>
          <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
            <div class="card-body text-center">
              <div>
                <h2>Sign up</h2>
                <p></p>
                <a href="{% url 'accounts:signup' %}?next={% url 'main:lesson_list' %}" class="btn btn-primary active mt-3">Sign up here!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
</body>
</html>

accounts/templates/accounts/signup.html
{% block content %}

{% load static %}


<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous" defer></script>

        <!--
    This website uses an MIT-licensed template.
    License information is available in the "license/license.text" file.
    -->


<link href="{% static 'accounts/log_sign.css' %}" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1">


<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="text-center mb-4">Sign up</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary btn-lg">Sign up</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<p><a href="{% url 'main:lesson_list' %}" class="btn btn-primary border border-dark">Go back to Iwade Schedule</a></p>
<p><a href="{% url 'main:bjj_lesson_list' %}" class="btn btn-primary border border-dark">Go back to Kix Schedule</a></p>


{% endblock %}