accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

main/urls.py
from django.urls import path, reverse_lazy
from . import views




app_name='main'
urlpatterns = [
    path('profile/<int:user_id>/', views.ProfilePageView.as_view(), name='profile'),
    path('iwade_lesson/list', views.LessonListView.as_view(), name='lesson_list'),
    path('profile/picture/<int:user_id>/', views.profile_stream_file, name='profile_picture'),
    path('button/<int:pk>/', views.ButtonPageView.as_view(), name='button_page'),
    path('button/<int:pk>/delete/<int:lesson_pk>/', views.ButtonDeleteView.as_view(success_url=reverse_lazy('main:button_page')), name='button_delete'),
    path('lesson/create/', views.LessonCreateView.as_view(), name='lesson_create'),
    path('lesson/<int:pk>/update/', views.LessonUpdateView.as_view(), name='lesson_update'),
    path('lesson/picture/<int:pk>/', views.stream_file, name='lesson_picture'),
    path('lesson/<int:pk>/delete', views.LessonDeleteView.as_view(success_url=reverse_lazy('main:lesson_list')), name='lesson_delete'),
    path('participation_increase/<int:pk>/<int:click_id>/', views.ParticipationIncreaseView.as_view(), name='participation_increase'),
    path('delete/<int:pk>/', views.AccountDeleteView.as_view(), name='delete_account'),
    path('', views.BjjLessonListView.as_view(), name='bjj_lesson_list'),
    path('set-user-limit/', views.SetUserLimitView.as_view(), name='set_user_limit'),
    path('reset_monthly_counts/', views.ResetMonthlyCountsView.as_view(), name='reset_monthly_counts'),
    path('profile/<int:user_id>/participation_count/', views.ParticipationCountView.as_view(), name='participation_count'),
    path('add_users_to_lessons/', views.AddUsersToLessonsView.as_view(), name='add_users_to_lessons'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),# Keep
]


# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]


# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

main/models.py
from django.db import models
from accounts.models import CustomUser
from django.utils import timezone


class Lesson(models.Model) :
    title = models.CharField(
            max_length=200,
    )

    # To decide which day in the schedule the lesson will be place in.
    DAY_CHOICES = [
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
    ]

    # To decide in which order from top to bottom of the scheule the lesson will be placed.
    SPOT_CHOICES = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]


    # The purpose of categories was originally to have a seperate count for each lesson category.
    # Still left this here as it can be nice to know the type of lesson anyways.
    CATEGORY_CHOICES = [
        ('Jiu Jitsu', 'Jiu Jitsu'),
        ('Free Mat', 'Free Mat'),
        ('Competition', 'Competition'),
        ('Basic', 'Basic'),
    ]

    # Color for the lesson title in the schedule.
    COLOR_CHOICES = [
        ('sky', 'Sky'),
        ('green', 'Green'),
        ('yellow', 'Yellow'),
        ('purple', 'Purple'),
        ('pink', 'Pink'),
        ('light red', 'Light Red'),
    ]

    # The owner got 2 gyms, so i made 2 seperate schedules.
    SCHOOL_CHOICES = [
        ('Kix', 'Kix'),
        ('Iwade', 'Iwade'),
    ]

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    day = models.CharField(max_length=10, choices=DAY_CHOICES, null=True)
    spot = models.IntegerField(choices=SPOT_CHOICES, null=True)
    text = models.TextField(null=True)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, null=True)
    color = models.CharField(max_length=20, choices=COLOR_CHOICES, null=True)
    time = models.CharField(max_length=12, null=True)
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    school = models.CharField(max_length=10, choices=SCHOOL_CHOICES, null=True)

class ParticipationCount(models.Model):
    # Taking monthly jiu jitsu participation counts and counts for each belt color.

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, null=True)

    monthly_count_j = models.PositiveIntegerField(default=0)

    white_jiu_jitsu_count = models.PositiveIntegerField(default=0)
    blue_jiu_jitsu_count = models.PositiveIntegerField(default=0)
    purple_jiu_jitsu_count = models.PositiveIntegerField(default=0)
    brown_jiu_jitsu_count = models.PositiveIntegerField(default=0)
    black_jiu_jitsu_count = models.PositiveIntegerField(default=0)




class Click(models.Model):
    # For putting members names into the lesson to increase their participationcounts later.

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, default=None)
    timestamp = models.DateTimeField(auto_now_add=True)
    order = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.user)

main/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.views import View
from main.models import Click, Lesson, ParticipationCount
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect
from accounts.models import CustomUser
from django.http import JsonResponse
from django.utils import timezone
from django.core import serializers





from main.forms import CreateForm, UserPreferencesForm, ParticipationCountForm
from django.contrib.auth.mixins import LoginRequiredMixin
from main.owner import OwnerDeleteView
from django.shortcuts import get_object_or_404
from django.http import HttpResponse





class SetUserLimitView(View):
    # For setting a limit to the number of members allowed.
    # This is being used with a middle ware that prevents access to the signup page if the limit is reached.
    template_name = 'main/profile.html'

    def post(self, request, *args, **kwargs):
        user_limit = request.POST.get('user_limit')
        current_user = self.request.user
        current_user.user_limit = int(user_limit)
        current_user.save()
        return redirect('main:profile', user_id=current_user.id)




class ProfilePageView(View):
    # View for displaying details of a member.
    # Includes various things like profile pic, belt color, participation counts etc.

    model = CustomUser
    template_name = 'main/profile.html'


    def get(self, request, user_id):
        # Gets the current belt, gym etc for the UserPreferencesForm.
        # And gets the current participation counts for the user as initial input in the form.
        user = get_object_or_404(CustomUser, id=user_id)
        users = CustomUser.objects.all()

        user_preferences_form = UserPreferencesForm(instance=user)

        participation_counts = ParticipationCount.objects.filter(user=user)

        total_white_count = sum(pc.white_jiu_jitsu_count for pc in participation_counts)
        total_blue_count = sum(pc.blue_jiu_jitsu_count for pc in participation_counts)
        total_purple_count = sum(pc.purple_jiu_jitsu_count for pc in participation_counts)
        total_brown_count = sum(pc.brown_jiu_jitsu_count for pc in participation_counts)
        total_black_count = sum(pc.black_jiu_jitsu_count for pc in participation_counts)


        participation_count_form = ParticipationCountForm(
            initial={
                'user': user,
                'white_jiu_jitsu_count': total_white_count,
                'blue_jiu_jitsu_count': total_blue_count,
                'purple_jiu_jitsu_count': total_purple_count,
                'brown_jiu_jitsu_count': total_brown_count,
                'black_jiu_jitsu_count': total_black_count,
            }
        )

        return render(request, self.template_name, {'user': user, 'users': users, 'user_preferences_form': user_preferences_form, 'participation_count_form': participation_count_form})

    def get_context_data(self, **kwargs):
        # To get the user of the current profile page.
        context = super(ProfilePageView, self).get_context_data(**kwargs)
        user_id = self.kwargs['user_id']

        user_id = int(user_id)

        context['user_id'] = user_id
        return context

    def post(self, request, user_id):
        # For changing information about the user using the form.

        user = get_object_or_404(CustomUser, id=user_id)
        users = CustomUser.objects.all()

        user_preferences_form = UserPreferencesForm(request.POST, request.FILES or None, instance=user)

        if user_preferences_form.is_valid():
            user_preferences_form.save()


            return redirect('main:profile', user_id=user.id)
        else:
            return render(request, self.template_name, {
                'user': user,
                'users': users,
                'user_preferences_form': user_preferences_form,
            })



def profile_stream_file(request, user_id):
    # This is got from the dj4e tutorial.
    # Lets you stream the picture in a different url and so I can use that link to display it on a page.

    user = get_object_or_404(CustomUser, id=user_id)
    response = HttpResponse()
    response['Content-Type'] = user.content_type
    response['Content-Length'] = len(user.profile_picture)
    response.write(user.profile_picture)
    return response



class ParticipationCountView(View):
    # Lets you change the participation count of a user manually using the form.

    template_name = 'main/profile.html'

    def post(self, request, user_id):
        user = get_object_or_404(CustomUser, id=user_id)

        ParticipationCount.objects.filter(user=user).delete()
        participation_count = ParticipationCount.objects.create(user=user)

        form = ParticipationCountForm(request.POST, instance=participation_count)

        if form.is_valid():


            participation_count.save()

            success_url = reverse('main:profile', kwargs={'user_id': participation_count.user.id})
            return redirect(success_url)
        else:
            return render(request, self.template_name, {'user': user, 'form': form, 'participation_count': participation_count})






class AddUsersToLessonsView(View):
    # Lets you add each member to all lessons of each respective school.

    template_name = 'main/bjj_lesson_list.html'

    def post(self, request, *args, **kwargs):
        kix_users = CustomUser.objects.filter(gym_choice='Kix')
        iwade_users = CustomUser.objects.filter(gym_choice='Iwade')
        both_users = CustomUser.objects.filter(gym_choice='Both')

        kix_lessons = Lesson.objects.filter(school='Kix')
        iwade_lessons = Lesson.objects.filter(school='Iwade')

        for user in kix_users:
            for lesson in kix_lessons:
                Click.objects.get_or_create(user=user, lesson=lesson)

        for user in iwade_users:
            for lesson in iwade_lessons:
                Click.objects.get_or_create(user=user, lesson=lesson)

        for user in both_users:
            for lesson in kix_lessons:
                Click.objects.get_or_create(user=user, lesson=lesson)

            for lesson in iwade_lessons:
                Click.objects.get_or_create(user=user, lesson=lesson)

        return HttpResponseRedirect(reverse('main:bjj_lesson_list'))



class ResetMonthlyCountsView(View):
    # Lets you reset all monthly jiu jitsu counts for all users.

    def get(self, request):
        all_users = CustomUser.objects.all()
        for user in all_users:
            participation_counts = ParticipationCount.objects.filter(user=user)
            for count in participation_counts:
                count.monthly_count_j = 0
                count.save()

        return HttpResponseRedirect(reverse('main:lesson_list'))





class AccountDeleteView(OwnerDeleteView):
    # Using the OwnerDeleteView I got from dj4e to delete accounts.

    model = CustomUser
    template_name = 'main/profile.html'

    def get_success_url(self):
        current_user_id = self.request.user.id
        return reverse('main:profile', kwargs={'user_id': current_user_id})


class LessonListView(View):
    # For displaying Iwade lessons on the page.

    model = Lesson
    template_name = "main/lesson_list.html"

    def get(self, request) :
        lesson_list = Lesson.objects.all()
        school = 'Iwade'
        day_choices = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
        spots = range(1, 6)

        ctx = {
            'lesson_list' : lesson_list,
            'school': school,
            'day_choices': day_choices,
            'spots': spots,
        }
        return render(request, self.template_name, ctx)

class BjjLessonListView(View):
    # For displaying Kix lessons on the page.

    model = Lesson
    template_name = "main/bjj_lesson_list.html"

    def get(self, request) :
        lesson_list = Lesson.objects.all()
        school = 'Kix'
        day_choices = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
        spots = range(1, 6)

        ctx = {
            'lesson_list' : lesson_list,
            'school': school,
            'day_choices': day_choices,
            'spots': spots,
        }
        return render(request, self.template_name, ctx)




class LessonCreateView(LoginRequiredMixin, View):
    # View for creating a lesson using the Createform.

    template_name = 'main/lesson_form.html'

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        if form.is_valid():
            day = form.cleaned_data['day']
            spot = form.cleaned_data['spot']
            school = form.cleaned_data['school']
            lesson_spot_used = Lesson.objects.filter(day=day, spot=spot, school=school).exists()

            if not lesson_spot_used:
                lesson = form.save(commit=False)
                lesson.owner = self.request.user
                lesson.save()
                if school == 'Iwade':
                    return redirect('main:lesson_list')
                elif school == 'Kix':
                    return redirect('main:bjj_lesson_list')
                else:
                    return redirect('main:lesson_list')
            else:
                ctx = {'form': form, 'error_message': 'This day and spot already exist.'}
                return render(request, self.template_name, ctx)
        else:
            ctx = {'form': form}
            return render(request, self.template_name, ctx)



class LessonUpdateView(LoginRequiredMixin, View):

    template_name = 'main/lesson_update.html'

    def get(self, request, pk):

main/templates/main/button_page.html
<!-- button_page.html -->
<!DOCTYPE html>
<html>
{% extends 'outlay.html' %}
{% load static %}
{% load my_tags %}
<head>
    <title>Participation Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

{% block head %}
<header class="masthead">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-7 py-5">
                <h1 class="mb-4">{% block page_title %}Triforce {{ lesson.school}} {{ lesson.category}} {{ lesson.day }} {{ lesson.time }}{% endblock %}</h1>
            </div>
            <div class="col-lg-5">
                <div class="py-5 px-4 masthead-cards">
                    <div class="d-flex">
                        <a {% if user.is_authenticated %} href="{% url 'main:profile' user.id %}"
                            {% else %} href="{% url 'accounts:login' %}?next={% url 'main:lesson_list' %}"
                            {% endif %} class="w-50 pr-3 pb-4">
                            <div class="card border-0 border-bottom-blue shadow-lg shadow-hover">
                                <div class="card-body text-center">
                                    <div class="text-center">
                                        <i class="fa fa-user fa-4x my-2" aria-hidden="true"></i>
                                    </div>
                                    Profile
                                </div>
                            </div>
                        </a>
                        <a {% if user.is_authenticated %} href="{% url 'accounts:logout' %}?next={% url 'main:lesson_list' %}"
                                 {% else %} href="{% url 'accounts:login' %}?next={% url 'main:lesson_list' %}"
                                 {% endif %} class="w-50 pl-3 pb-4">
                            <div class="card border-0 border-bottom-blue shadow-lg shadow-hover">
                                <div class="card-body text-center">
                                    <div class="text-center">
                                        <i class="fa fa-sign-in fa-4x my-2" aria-hidden="true"></i>
                                    </div>
                                    {% if user.is_authenticated %}
                                    Logout
                                    {% else %}
                                    Login
                                    {% endif %}
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="d-flex">
                        <a href="{% url 'main:bjj_lesson_list' %}" class="w-50 pr-3">
                            <div class="card border-0 border-bottom-yellow shadow-lg shadow-hover">
                                <div class="card-body text-center">
                                    <div class="text-center">
                                        <img src="{% static 'main/download.jpg' %}" alt="" style="width: 120px; height: 68px;">
                                    </div>
                                    Triforce Kix
                                </div>
                            </div>
                        </a>
                        <a href="{% url 'main:lesson_list' %}" class="w-50 pl-3">
                            <div class="card border-0 border-bottom-green shadow-lg shadow-hover">
                                <div class="card-body text-center">
                                    <div class="text-center">
                                        <img src="{% static 'main/IWADE.png' %}" alt="" style="width: 120px; height: 68px;">
                                    </div>
                                    Triforce Iwade
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="shape"></div>
                </div>
            </div>
        </div>
    </div>
    <svg style="pointer-events: none" class="wave" width="100%" height="50px" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1920 75">
        <defs>
            <style>
                .a {
                    fill: none;
                }

                .b {
                    clip-path: url(#a);
                }

                .c,
                .d {
                    fill: #f9f9fc;
                }

                .d {
                    opacity: 0.5;
                    isolation: isolate;
                }
            </style>
            <clipPath id="a">
                <rect class="a" width="1920" height="75"></rect>
            </clipPath>
        </defs>
        <title>wave</title>
        <g class="b">
            <path class="c" d="M1963,327H-105V65A2647.49,2647.49,0,0,1,431,19c217.7,3.5,239.6,30.8,470,36,297.3,6.7,367.5-36.2,642-28a2511.41,2511.41,0,0,1,420,48"></path>
        </g>
        <g class="b">
            <path class="d" d="M-127,404H1963V44c-140.1-28-343.3-46.7-566,22-75.5,23.3-118.5,45.9-162,64-48.6,20.2-404.7,128-784,0C355.2,97.7,341.6,78.3,235,50,86.6,10.6-41.8,6.9-127,10"></path>
        </g>
        <g class="b">
            <path class="d" d="M1979,462-155,446V106C251.8,20.2,576.6,15.9,805,30c167.4,10.3,322.3,32.9,680,56,207,13.4,378,20.3,494,24"></path>
        </g>
        <g class="b">
            <path class="d" d="M1998,484H-243V100c445.8,26.8,794.2-4.1,1035-39,141-20.4,231.1-40.1,378-45,349.6-11.6,636.7,73.8,828,150"></path>
        </g>
    </svg>
</header>
{% endblock %}

<link href="{% static 'main/timetable.css' %}" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
{% block body %}
<div id="scroll-target" class="container">
<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row row-with-horizontal-scroll">
                {% if not request.user.is_superuser %}
                <div class="col-lg-5 col-md-5 col-sm-6">
                    <div class="white-box text-center"><img style="width:270px; height:300px; margin-top:8px; border:3px solid black;" src="{% url 'main:lesson_picture' lesson.pk %}" class="img-responsive"></div>
                </div>
                {% endif %}
                <div class="col-lg-7 col-md-7 col-sm-6">
                    <h4 class="box-title mt-5">{{ lesson.title }}</h4>
                    {{ lesson.day }}
                    {{ lesson.school }}
                    {{ lesson.category|safe }}
                    {{ lesson.time|safe }}
                    {{ lesson.text|safe }}
                    {% if not request.user.is_superuser %}
                    <h2> Members </h2>
                    <form method="POST" action="">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary btn-rounded border border-dark" value="Add to the list">
                    </form>
                    {% endif %}
                    <ul>
                        {% for click in clicks|dictsortreversed:"timestamp" %}
                        <li style="border: 3px solid black; padding: 5px; margin-bottom: 5px; overflow: auto;">
                            <div>
                                <img style="width:64px;height:64px;margin-top: 8px; border:3px solid black;" {% if request.user.is_superuser %}src="{% url 'main:profile_picture' click.user.id %}"{% else %}src="{% static 'main/32fb4d73a44991984a007252e99f93c7.jpg' %}"{% endif %}>
                            <span style="margin-left: 10px;">
                                    <span style="margin-right: 20px; color:
    {% if click.user.belt == 'White' %} white; text-shadow: -1px -1px 0 black, 1px -1px 0 black, -1px 1px 0 black, 1px 1px 0 black;
    {% elif click.user.belt == 'Blue' %} blue; font-weight: bold;
    {% elif click.user.belt == 'Purple' %} purple; font-weight: bold;
    {% elif click.user.belt == 'Brown' %} brown; font-weight: bold;
    {% elif click.user.belt == 'Black' %} black; font-weight: bold;
    {% else %} default_color; {% endif %}">
                                    {{ click }}
                                    </span>
                                {{ click.timestamp|date:"Y-m-d" }}
                            </span>
                            </div>
                            <div style="display: flex; align-items: center;">
                            {% if click.user == request.user %}
                                <form action="{% url 'main:button_delete' click.id lesson.pk %}" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-danger btn-rounded border border-dark" value="Remove yourself from lesson">
                                </form>
                            {% elif request.user.is_superuser %}
                                <form>
                                {% csrf_token %}
                                <button type="button" class="increase-participation btn btn-primary border border-dark border-2 mt-2" data-url="{% url 'main:participation_increase' lesson.pk click.id %}">
                                {% if click.user.belt == "White" %}
                                    {% white_jiu_jitsu_message click.user.id %}
                                {% elif click.user.belt == "Blue" %}
                                    {% blue_jiu_jitsu_message click.user.id %}
                                {% elif click.user.belt == "Purple" %}
                                    {% purple_jiu_jitsu_message click.user.id %}
                                {% elif click.user.belt == "Brown" %}
                                    {% brown_jiu_jitsu_message click.user.id %}
                                {% endif %}
                                Participated!
                                {% if click.user.belt == "White" %}
                                    <span id="white_jiu_jitsu_count">{% white_jiu_jitsu_participation_count click.user.id %}</span>
                                {% elif click.user.belt == "Blue" %}
                                    <span id="blue_jiu_jitsu_count">{% blue_jiu_jitsu_participation_count click.user.id %}</span>
                                {% elif click.user.belt == "Purple" %}
                                    <span id="purple_jiu_jitsu_count">{% purple_jiu_jitsu_participation_count click.user.id %}</span>
                                {% elif click.user.belt == "Brown" %}
                                    <span id="brown_jiu_jitsu_count">{% brown_jiu_jitsu_participation_count click.user.id %}</span>
                                {% elif click.user.belt == "Black" %}
                                    <span id="black_jiu_jitsu_count">{% black_jiu_jitsu_participation_count click.user.id %}</span>
                                {% endif %}
                                </button>
                                </form>
                            {% endif %}
                            </div>
                        </li>
                        {% endfor %}
                    </div>
                    </div>
                    </ul>
                    <p><a href="{% url 'main:lesson_list' %}" class="btn btn-primary border border-dark">Go back to Iwade schedule</a></p>
                    <p><a href="{% url 'main:bjj_lesson_list' %}" class="btn btn-primary border border-dark">Go back to Kix schedule</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<a href="{% url 'main:lesson_update' pk=lesson.pk %}" class="btn btn-success border border-dark">Update Lesson</a>

<p></p>
<div>
    {% if request.user.is_superuser %}
    <button class="btn btn-danger border border-dark" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal">Delete Lesson</button>
    {% endif %}
</div>

<div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmDeleteModalLabel">Delete confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Do you really want to delete this lesson?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancle</button>
                <form action="{% url 'main:lesson_delete' lesson.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous" defer></script>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{% static 'main/button.js' %}?v=1"></script>
<script src="{% static 'main/scroll.js' %}"></script>
{% endblock %}
</html>

main/templates/main/lesson_form.html
{% extends 'outlay.html' %}
{% load static %}
<head>
    <title>Lesson create form</title>
</head>

{% block body%}
<body>
    <h1>Create Lesson</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if request.user.is_superuser %}
        <button type="submit" class="btn btn-success border border-dark">Save Lesson</button>
        {% endif %}
    </form>
    <p></p>
    <p><a href="{% url 'main:lesson_list' %}" class="btn btn-primary border border-dark">Go back to Iwade schedule</a></p>
    <p><a href="{% url 'main:bjj_lesson_list' %}" class="btn btn-primary border border-dark">Go back to Kix schedule</a></p>
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous" defer></script>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{% static 'main/scroll.js' %}"></script>
{% endblock %}